export const ActionTypes = {
    FETCH_TRACKS: 'FETCH_TRACKS',
    FETCH_ARTIST: 'FETCH_ARTIST',
    FETCH_SEARCHED_TRACKS: 'FETCH_SEARCHED_TRACKS',
    REMOVE_SELECTED_ARTIST: 'REMOVE_SELECTED_ARTIST',
    REMOVE_SEARCHED_TRACKS: 'REMOVE_SEARCHED_TRACKS'
};